on:
   push:
     branches: [main]

env:
  WORKSPACE: ${{ github.workspace }}
  KERNEL: "${{ github.workspace }}/kernel"

jobs:
  build:
    runs-on: ubuntu-22.04
   
    permissions:
      contents: write
     
    defaults:
      run:
        shell: bash
   
    steps:
    - uses: actions/checkout@v4
    
    - name: free_disk_space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: install_packages
      working-directory: ${{ github.workspace }}
      run: |
        sudo apt update && sudo apt upgrade -y

        # delete this
        sudo apt remove -y lib32ncurses5-dev || true
        
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf libncurses-dev libz-dev libxml2-utils xsltproc zip zlib1g-dev python3 repo abootimg

    - name: clone_twrp_a145p
      working-directory: ${{ github.workspace }}
      run: |
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1 abootimg

        repo sync -j$(nproc) --force-sync

    - name: get_image
      working-directory: ${{ github.workspace }}
      run: |
        abootimg -x boot.img
        
        mv zImage Image

    - name: clone_device_tree
      working-directory: ${{ github.workspace }}
      run: |
        git clone https://github.com/forforksake/recovery_device_samsung_a14m.git a145m

        ls -a

    - name: clone_blobs
      working-directory: ${{ github.workspace }}
      run: |
        TREE="a145m"
        
