on:
   push:
     branches: [main]

env:
  WORKSPACE: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
   
    permissions:
      contents: write
     
    defaults:
      run:
        shell: bash
   
    steps:
    - uses: actions/checkout@v4
    
    - name: free_disk_space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: install_packages
      working-directory: ${{ github.workspace }}
      run: |
        sudo apt update && sudo apt upgrade -y

        sudo apt remove -y lib32ncurses5-dev || true
        
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf libncurses-dev libz-dev libxml2-utils xsltproc zip zlib1g-dev python3 repo abootimg

    - name: clone_twrp
      working-directory: ${{ github.workspace }}
      run: |
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1 --depth=1

        repo sync -j$(nproc) --force-sync --no-clone-bundle --no-tags

    - name: Clone device tree
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p ~/twrp/device/samsung

        git clone https://github.com/forforksake/recovery_device_samsung_a14m.git ~/twrp/device/samsung/a145m
        
    - name: copy_blobs
      working-directory: ${{ github.workspace }}
      run: |
        cp -r ./a14m/recovery ~/twrp/device/samsung/a145m/
        
    - name: replace_image
      working-directory: ${{ github.workspace }}
      run: |
        mkdir -p ./twrp/device/samsung/a145m/prebuilt

        cp ./Image ./twrp/device/samsung/a145m/prebuilt/Image

        echo "TARGET_PREBUILT_KERNEL := \$(DEVICE_PATH)/prebuilt/Image" >> ./twrp/device/samsung/a145m/BoardConfig.mk
